version: '3.8'

services:
  # Redis - shared state
  redis:
    image: redis:7-alpine
    container_name: autogen-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - autogen-network
    ports:
      - "6379:6379"

  # Central Manager
  central-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autogen-central-manager
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./autogen.db
      - ENABLE_DISTRIBUTED=true
      - DISCOVERY_INTERVAL=30
      - HEALTH_CHECK_INTERVAL=15
      - REBALANCE_INTERVAL=300
      - JWT_SECRET=super-secret-jwt-key-for-autogen-platform-2024-32chars
      - ADMIN_PASSWORD=default-admin-password-change-in-production-32chars!
      - LOG_LEVEL=INFO
      - MASTER_SECRET_KEY=master-secret-key-for-secure-inter-instance-comm-32chars!
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - autogen-network
    volumes:
      - ./app:/app/app
      - ./keys:/app/keys
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "autogen.role=central-manager"

  # Agent Container 1 - Trading Focus
  agent-container-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: autogen-agent-01
    environment:
      - AGENT_ID=agent-container-01
      - AGENT_TYPE=trading
      - AGENT_PORT=8001
      - REDIS_URL=redis://redis:6379
      - CENTRAL_MANAGER_URL=http://central-manager:8000
      - ADMIN_PASSWORD=default-admin-password-change-in-production-32chars!
      - CONTAINER_NAME=trading-node-01
      - AGENT_CONFIG={"capabilities":["trading","market_analysis"],"max_agents":5}
    depends_on:
      - redis
      - central-manager
    networks:
      - autogen-network
    ports:
      - "8001:8001"
    labels:
      - "autogen.agent.capable=true"
      - "autogen.agent.type=trading"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Agent Container 2 - Analysis Focus
  agent-container-2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: autogen-agent-02
    environment:
      - AGENT_ID=agent-container-02
      - AGENT_TYPE=analysis
      - AGENT_PORT=8001
      - REDIS_URL=redis://redis:6379
      - CENTRAL_MANAGER_URL=http://central-manager:8000
      - ADMIN_PASSWORD=default-admin-password-change-in-production-32chars!
      - CONTAINER_NAME=analysis-node-01
      - AGENT_CONFIG={"capabilities":["analysis","gpu_compute"],"max_agents":3}
    depends_on:
      - redis
      - central-manager
    networks:
      - autogen-network
    ports:
      - "8002:8001"
    labels:
      - "autogen.agent.capable=true"
      - "autogen.agent.type=analysis"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  # Agent Container 3 - Risk Management Focus
  agent-container-3:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: autogen-agent-03
    environment:
      - AGENT_ID=agent-container-03
      - AGENT_TYPE=risk
      - AGENT_PORT=8001
      - REDIS_URL=redis://redis:6379
      - CENTRAL_MANAGER_URL=http://central-manager:8000
      - ADMIN_PASSWORD=default-admin-password-change-in-production-32chars!
      - CONTAINER_NAME=risk-node-01
      - AGENT_CONFIG={"capabilities":["risk_analysis","compliance"],"max_agents":2}
    depends_on:
      - redis
      - central-manager
    networks:
      - autogen-network
    ports:
      - "8003:8001"
    labels:
      - "autogen.agent.capable=true"
      - "autogen.agent.type=risk"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Optional: Additional generic worker containers
  agent-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: autogen-worker-01
    environment:
      - AGENT_ID=agent-worker-01
      - AGENT_TYPE=generic
      - AGENT_PORT=8001
      - REDIS_URL=redis://redis:6379
      - CENTRAL_MANAGER_URL=http://central-manager:8000
      - ADMIN_PASSWORD=default-admin-password-change-in-production-32chars!
      - CONTAINER_NAME=worker-node-01
      - AGENT_CONFIG={"capabilities":["general_compute"],"max_agents":10}
    depends_on:
      - redis
      - central-manager
    networks:
      - autogen-network
    labels:
      - "autogen.agent.capable=true"
      - "autogen.agent.type=generic"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  autogen-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  redis-data: