version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-please-change-me}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - autogen-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - autogen-network

  # Optional: OpenBB service for financial data
  openbb:
    build: ./app/openbb
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - autogen-network
    profiles:
      - financial

networks:
  autogen-network:
    driver: bridge