services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - TWELVEDATA_API_KEY=${TWELVEDATA_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - INITIAL_CAPITAL=${INITIAL_CAPITAL:-1000.00}
      - MAX_POSITION_PCT=${MAX_POSITION_PCT:-0.10}
      - STOP_LOSS_PCT=${STOP_LOSS_PCT:-0.02}
      - COMMISSION_PCT=${COMMISSION_PCT:-0.001}
      - TARGET_SYMBOLS=${TARGET_SYMBOLS:-AAPL,MSFT,GOOGL,TSLA,NVDA,BTC-USD,ETH-USD}
      - ENABLE_MEAN_REVERSION=${ENABLE_MEAN_REVERSION:-true}
      - ENABLE_MOMENTUM=${ENABLE_MOMENTUM:-true}
      - ENABLE_ARBITRAGE=${ENABLE_ARBITRAGE:-true}
      - ENABLE_SCALPING=${ENABLE_SCALPING:-false}
      - ENABLE_DCA=${ENABLE_DCA:-true}
      - DAILY_LOSS_LIMIT=${DAILY_LOSS_LIMIT:-0.05}
      - MAX_DAILY_TRADES=${MAX_DAILY_TRADES:-50}
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.6}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - trading_data:/app/data
      - audit_logs:/var/log/trading
      - backups:/app/backups
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
      - redis_backup:/backup
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --save 900 100
      --appendonly yes
      --appendfsync everysec
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru

volumes:
  trading_data:
    driver: local
  audit_logs:
    driver: local
  backups:
    driver: local
  redis_data:
    driver: local
  redis_backup:
    driver: local

networks:
  trading-network:
    driver: bridge