services:
  gateway:
    image: livepeer/go-livepeer:sha-5627b90
    container_name: byoc-gateway-test
    volumes:
      - ./data/gateway:/data
    ports:
      - 9999:9999
    command: ["-gateway",
          "-orchAddr=",
          "-httpAddr=gateway:9999",
          "-httpIngest=true",
          "-maxTicketEV=300000000000000",
          "-maxTotalEV=300000000000000",
          "-maxFaceValue=1000000000000000",
          "-maxPricePerUnit=130000000000000", #device per unit is irrelevant in current BYOC builds but might cause error if bellow what orch has set
          "-v=6",
          "-network=arbitrum-one-mainnet",
          "-ethUrl=https://arb1.arbitrum.io/rpc",
          "-ethPassword=STRONG_PASSWORD_HERE",
          "-dataDir=/data"]
    networks:
      - default

networks:
  default:
    name: byoc
    external: true 